name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image to Docker registry
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          build-args: JAVA_VER=java17,GRAALVM_VER=21.3.0
          platforms: linux/amd64,linux/arm64
          tags: |
            zapp88/graalvm-multiarch:java11-21.3.0
            zapp88/graalvm-multiarch:java11-latest
