name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zapp88/graalvm-multiarch:linux-x86_64
      
    - name: Push image to Docker registry
      uses: docker/build-push-action@v2.8.0
      with:
          push: true
          tags: zapp88/graalvm-multiarch:linux-x86_64
       
