name: Publish latest java 11 manifest

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull images
        run: |
          docker pull zapp88/graalvm-multiarch:amd64-java11-graalvm21.3.0
          docker pull zapp88/graalvm-multiarch:arm64-java11-graalvm21.3.0
      - name: Amend manifest
        run: |
          docker manifest create zapp88/graalvm-multiarch:java11-graalvm21.3.0 --amend zapp88/graalvm-multiarch:amd64-java11-graalvm21.3.0 --amend zapp88/graalvm-multiarch:arm64-java11-graalvm21.3.0
          docker manifest push zapp88/graalvm-multiarch:java11-graalvm21.3.0
      - name: Amend manifest latest
        run: |
          docker manifest create zapp88/graalvm-multiarch:java11-latest --amend zapp88/graalvm-multiarch:amd64-java11-graalvm21.3.0 --amend zapp88/graalvm-multiarch:arm64-java11-graalvm21.3.0
          docker manifest push zapp88/graalvm-multiarch:java11-latest
